{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yaonet-ingress
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
  {{- if .Values.ingress.managedCertificate.enabled }}
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "yaonet-ip"
    networking.gke.io/managed-certificates: "yaonet-managed-cert"
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.hosts }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ .Values.web.name }}
            port:
              number: {{ .Values.web.service.port }}
      {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
---
{{- if .Values.ingress.managedCertificate.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: yaonet-managed-cert
  namespace: {{ .Values.namespace.name }}
spec:
  domains:
  {{- range .Values.ingress.managedCertificate.domains }}
  - {{ . | quote }}
  {{- end }}
{{- end }}
{{- end }}
