{{- if .Values.workloadIdentity.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workloadIdentity.kubernetesServiceAccount }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.workloadIdentity.googleServiceAccount }}
{{- end }}
