#!/bin/bash

# ☁️ Google Cloud Run Deployment - Setup Script
# This script helps you set up your deployment credentials

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLOUD_DEPLOYMENT_DIR="$SCRIPT_DIR"
PROJECT_ROOT="$(dirname "$CLOUD_DEPLOYMENT_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}☁️  Google Cloud Run Deployment Setup${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Check if .env.cloud already exists
if [ -f "$CLOUD_DEPLOYMENT_DIR/.env.cloud" ]; then
    # Check if it's just the placeholder
    if grep -q "DO NOT EDIT THIS FILE" "$CLOUD_DEPLOYMENT_DIR/.env.cloud"; then
        echo -e "${YELLOW}📝 Creating your .env.cloud file...${NC}"
        cp "$CLOUD_DEPLOYMENT_DIR/.env.cloud.example" "$CLOUD_DEPLOYMENT_DIR/.env.cloud"
        echo -e "${GREEN}✅ Created: $CLOUD_DEPLOYMENT_DIR/.env.cloud${NC}"
    else
        echo -e "${GREEN}✅ .env.cloud already exists${NC}"
    fi
else
    echo -e "${YELLOW}📝 Creating your .env.cloud file...${NC}"
    cp "$CLOUD_DEPLOYMENT_DIR/.env.cloud.example" "$CLOUD_DEPLOYMENT_DIR/.env.cloud"
    echo -e "${GREEN}✅ Created: $CLOUD_DEPLOYMENT_DIR/.env.cloud${NC}"
fi

echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}📋 Next Steps${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "1️⃣  Open the configuration file:"
echo -e "   ${YELLOW}nano $CLOUD_DEPLOYMENT_DIR/.env.cloud${NC}"
echo ""
echo "2️⃣  Fill in your credentials:"
echo "   • GCP_PROJECT_ID: From Google Cloud Console"
echo "   • DOCKER_USERNAME: Your Docker Hub username"
echo "   • DATABASE_URL: From Neon.tech connection string"
echo "   • REDIS_URL: From Upstash.com Redis URL"
echo ""
echo "3️⃣  Load the variables before deployment:"
echo -e "   ${YELLOW}source $CLOUD_DEPLOYMENT_DIR/.env.cloud${NC}"
echo ""
echo "4️⃣  Run deployment:"
echo -e "   ${YELLOW}bash $CLOUD_DEPLOYMENT_DIR/scripts/test-cloud-deployment.sh${NC}"
echo ""
echo -e "${GREEN}✅ Setup complete! Edit .env.cloud and you're ready to deploy.${NC}"
echo ""
echo -e "${YELLOW}🔒 Reminder: .env.cloud is git-ignored for security${NC}"
echo ""
