[program:yaonet]
command=/home/ubuntu/yaonet/venv/bin/gunicorn -b localhost:8000 -w 4 yaonet:app
directory=/home/ubuntu/yaonet
user=ubuntu
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
