[program:yaonet-tasks]
command=/home/ubuntu/yaonet/venv/bin/rq worker yaonet-tasks
numprocs=1
directory=/home/ubuntu/yaonet
user=ubuntu
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
