apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgres.database | quote }}
